layout_spectrum: 0.541514453516978
typography_spectrum: 0.9087233675957317
color:
  brandStrength: 0.7274873159634927
  lightness: 0.6722946056070748
  saturation: 0.6417068947314994
  rhythmicContrast: 0.42049835034544664
  brandColors:
    - '#FFFFFF'
    - '#FF6634'
    - '#333333'
    - '#B3B3B3'
    - '#5C8525'
github: true
author:
  name: Zachary Strider McGregor-Dorsey
  email: tarrou@alum.mit.edu
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/041c701a-2704-47a0-a783-3d241b41032e.jpg
name: The Dorsey-Lees
navigation:
  - name: Official Family Blog
    url: 'http://wadudunamaharage.blogspot.com/'
    type: external
  - name: About us
    id: d680bde3-1f26-4c07-ba70-dccb84454bee
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ef54383b-b88b-4adb-9f6c-bfe753056432.jpg
title: ME and KZ and ??
content: []
description: 'Becoming Human, a Dorsey-Lee Project'
purpose:
  - type: contact
    url: 'mailto:tarrou@alum.mit.edu'
    label: Contact father
  - type: contact
    url: 'mailto:jessicalee.tz@gmail.com'
    label: Contact mother
